# Generated by Django 4.0.1 on 2022-01-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Sid',
            new_name='roll_no',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Cid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Sname',
        ),
        migrations.AddField(
            model_name='student',
            name='First_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Cname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
