# Generated by Django 4.0.1 on 2022-02-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_sid_student_roll_no_remove_course_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
