# Generated by Django 4.0.1 on 2022-02-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
    ]
