# Generated by Django 4.0.1 on 2022-02-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='Cname',
        ),
    ]
