# Generated by Django 4.0.1 on 2023-01-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Ccode',
            field=models.IntegerField(default=0),
        ),
    ]
